# Generated by Django 5.2.10 on 2026-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='Product',
            new_name='product',
        ),
    ]
